/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.home.security.view;

import javax.swing.SwingUtilities;
import smart.home.security.model.Device;
import smart.home.security.model.Devices;
import smart.home.security.utilities.AudioManager;
import smart.home.security.utilities.DeviceSocketManager;

/**
 *
 * @author shahi
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        updateStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        armButton = new javax.swing.JButton();
        disarmButton = new javax.swing.JButton();
        enableButton = new javax.swing.JButton();
        disableButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SMART HOME SECURITY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(408, 309));

        addButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addButton.setText("ADD");
        addButton.setToolTipText("Add a device");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        removeButton.setText("REMOVE");
        removeButton.setToolTipText("Remove a device");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        armButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        armButton.setText("ARM");
        armButton.setToolTipText("Arm system");
        armButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armButtonActionPerformed(evt);
            }
        });

        disarmButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        disarmButton.setText("DISARM");
        disarmButton.setToolTipText("Disarm system");
        disarmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disarmButtonActionPerformed(evt);
            }
        });

        enableButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        enableButton.setText("ENABLE");
        enableButton.setToolTipText("Enable device");
        enableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableButtonActionPerformed(evt);
            }
        });

        disableButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        disableButton.setText("DISABLE");
        disableButton.setToolTipText("Disable a device");
        disableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableButtonActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        statusLabel.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(armButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disarmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(armButton)
                        .addComponent(enableButton)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(disarmButton)
                        .addComponent(disableButton)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("-----------------SMART HOME SECURITY");
    }// </editor-fold>//GEN-END:initComponents

    private SmartHomeSecurityFrame getSmartHomeSecurityFrame() {
        return SmartHomeSecurityFrame.getInstance();
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AvailableDevicesPanel availableDevicesPanel = new AvailableDevicesPanel();
        getSmartHomeSecurityFrame().replaceFramePanel(availableDevicesPanel);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        RemoveDevicePanel removeDevicePanel = new RemoveDevicePanel();
        getSmartHomeSecurityFrame().replaceFramePanel(removeDevicePanel);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void armButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armButtonActionPerformed
        Devices.getInstance().armDevices();
        for (Device device : Devices.getInstance().getDevices()) {
            DeviceSocketManager.getInstance().sendDeviceMessage(device);
        }
        updateStatus();
        AudioManager audioManager = new AudioManager();
        audioManager.playAudio(AudioManager.SYSTEM_ARMED);
    }//GEN-LAST:event_armButtonActionPerformed

    private void disarmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disarmButtonActionPerformed
        Devices.getInstance().disarmDevices();
        for (Device device : Devices.getInstance().getDevices()) 
        {
            DeviceSocketManager.getInstance().sendDeviceMessage(device);
        }
        updateStatus();
        AudioManager audioManager = new AudioManager();
        audioManager.playAudio(AudioManager.SYSTEM_DISARMED);
    }//GEN-LAST:event_disarmButtonActionPerformed

    private void enableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableButtonActionPerformed
        EnablePanel enablePanel = new EnablePanel();
        getSmartHomeSecurityFrame().replaceFramePanel(enablePanel);
    }//GEN-LAST:event_enableButtonActionPerformed

    private void disableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableButtonActionPerformed
        DisablePanel disablePanel = new DisablePanel();
        getSmartHomeSecurityFrame().replaceFramePanel(disablePanel);
    }//GEN-LAST:event_disableButtonActionPerformed

    private void updateStatus() {
        if (Devices.getInstance().armed()) {
            statusLabel.setText("ARMED");
        } else {
            statusLabel.setText("DISARMED");
        }
        armButton.setEnabled(Devices.getInstance().canArmDevices());
        disarmButton.setEnabled(Devices.getInstance().canDisarmDevices());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton armButton;
    private javax.swing.JButton disableButton;
    private javax.swing.JButton disarmButton;
    private javax.swing.JButton enableButton;
    private javax.swing.JButton removeButton;
    public javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
